# This is a config for E2B sandbox template.
# You can use template ID (35say9dtojwu03w1zcm9) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("35say9dtojwu03w1zcm9") # Sync sandbox
# sandbox = await AsyncSandbox.create("35say9dtojwu03w1zcm9") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('35say9dtojwu03w1zcm9')

team_id = "d247be2f-9ee9-4ee5-891c-01d5f9c513f2"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "35say9dtojwu03w1zcm9"
